#
# This pipeline needs the following tasks from Tekton Hub:
#   - git-clone
#   - flake8
#   - cleanup (custom task)
#   - nose (custom task for testing)
#   - buildah (ClusterTask for building images)
#
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:  
  name: cd-pipeline
spec:
  workspaces:
    - name: shared-workspace
  params:
    - name: repo-url
      description: "Git repository URL to clone"
    - name: branch
      description: "Branch to checkout"
      default: main
    - name: build-image
      description: "Destination image for the build"
      default: "my-app:latest"
  tasks:
    - name: init
      workspaces:
        - name: source
          workspace: shared-workspace
      taskRef:
        name: cleanup

    - name: clone
      workspaces:
        - name: output
          workspace: shared-workspace
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)
      runAfter:
        - init

    - name: lint
      workspaces:
        - name: source
          workspace: shared-workspace
      taskRef:
        name: flake8
      params:
        - name: image
          value: "python:3.9-slim"
        - name: args
          value:
            - "--count"
            - "--max-complexity=10"
            - "--max-line-length=127"
            - "--statistics"
      runAfter:
        - clone

    - name: tests
      workspaces:
        - name: source
          workspace: shared-workspace
      taskRef:
        name: nose
      params:
        - name: database_uri
          value: "sqlite:///test.db"
        - name: args
          value:
            - "-v"
            - "--with-spec"
            - "--spec-color"
      runAfter:
        - clone

    - name: build
      workspaces:
        - name: source
          workspace: shared-workspace
      taskRef:
        name: buildah
        kind: ClusterTask
      params:
        - name: IMAGE
          value: "$(params.build-image)"
      runAfter:
        - tests
        - lint
